project:
  type: website
  output-dir: docs

website:
  title: "Félix Laplante"
  navbar:
    logo: assets/logo.svg
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: talks.qmd
        text: Talks

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
