project:
  type: website
  output-dir: docs

website:
  title: "Félix Laplante"
  navbar:
    logo: assets/logo.svg
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: talks.qmd
        text: Talks
      - href: contact.qmd
        text: Contact
    right:
      - icon: envelope
        href: mailto:research.felixlaplante@gmail.com
        aria-label: Email
      - icon: github
        href: https://github.com/felixlaplante0
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
