project:
  type: website
  output-dir: docs

website:
  title: "Félix Laplante"
  sitemap: true
  navbar:
    logo: assets/logo.svg
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: talks.qmd
        text: Talks
      - href: contact.qmd
        text: Contact
    right:
      - icon: envelope
        href: mailto:research.felixlaplante@gmail.com
        aria-label: Email
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=uRGOOqIAAAAJ
        aria-label: Google Scholar
      - icon: github
        href: https://github.com/felixlaplante0
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/felix-laplante/
        aria-label: LinkedIn

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

resources:
  - google58feed90c4473f70.html
